# Generated by Django 3.2 on 2023-07-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDinnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_bill_phone_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_phone_cash_count', models.IntegerField(default=0)),
                ('real_bill_phone_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_phone_card_count', models.IntegerField(default=0)),
                ('real_bill_online_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_online_cash_count', models.IntegerField(default=0)),
                ('real_bill_online_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_online_card_count', models.IntegerField(default=0)),
                ('real_bill_in_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_in_cash_count', models.IntegerField(default=0)),
                ('real_bill_in_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_in_card_count', models.IntegerField(default=0)),
                ('pos_ta_bill_phone_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos_ta_bill_phone_cash_count', models.IntegerField(default=0)),
                ('pos_ta_bill_phone_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos_ta_bill_phone_card_count', models.IntegerField(default=0)),
                ('pos_in_bill_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos_in_bill_cash_count', models.IntegerField(default=0)),
                ('pos_in_bill_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos_in_bill_card_count', models.IntegerField(default=0)),
                ('edc_in_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detail_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BillLunchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_bill_phone_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_phone_cash_count', models.IntegerField(default=0)),
                ('real_bill_phone_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_phone_card_count', models.IntegerField(default=0)),
                ('real_bill_online_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_online_cash_count', models.IntegerField(default=0)),
                ('real_bill_online_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_online_card_count', models.IntegerField(default=0)),
                ('real_bill_in_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_in_cash_count', models.IntegerField(default=0)),
                ('real_bill_in_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('real_bill_in_card_count', models.IntegerField(default=0)),
                ('pos_ta_bill_phone_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos_ta_bill_phone_cash_count', models.IntegerField(default=0)),
                ('pos_ta_bill_phone_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos_ta_bill_phone_card_count', models.IntegerField(default=0)),
                ('pos_in_bill_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos_in_bill_cash_count', models.IntegerField(default=0)),
                ('pos_in_bill_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos_in_bill_card_count', models.IntegerField(default=0)),
                ('edc_in_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detail_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(default='', max_length=100)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wageperhr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EdcDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('detail_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PosDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_count', models.IntegerField(default=0)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_count', models.IntegerField(default=0)),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pos_type', models.CharField(max_length=100)),
                ('checkout_status', models.IntegerField(default=0)),
                ('detail_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.billlunchmodel')),
                ('delivery_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.deliverydetailmodel')),
                ('edc_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.edcdetailmodel')),
                ('pos_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordapp.posdetailmodel')),
            ],
        ),
    ]
