# Generated by Django 3.2 on 2023-08-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdinnermodel',
            name='pos_dine_in_total_bill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='pos_ta_phone_total_bill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billlunchmodel',
            name='pos_dine_in_total_bill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billlunchmodel',
            name='pos_ta_phone_total_bill_count',
            field=models.IntegerField(default=0),
        ),
    ]
