# Generated by Django 3.2 on 2023-07-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EdcDetailModel',
        ),
        migrations.DeleteModel(
            name='PosDetailModel',
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='real_bill_home_online_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='real_bill_home_online_card_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='real_bill_home_online_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='real_bill_home_online_cash_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='real_bill_home_phone_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='real_bill_home_phone_card_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='real_bill_home_phone_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='real_bill_home_phone_cash_count',
            field=models.IntegerField(default=0),
        ),
    ]
