# Generated by Django 3.2 on 2023-07-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0005_alter_billdinnermodel_edc_home_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdinnermodel',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billlunchmodel',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
