# Generated by Django 3.2 on 2023-07-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0006_auto_20230725_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billdinnermodel',
            old_name='tip',
            new_name='tip_cash',
        ),
        migrations.RenameField(
            model_name='billlunchmodel',
            old_name='tip',
            new_name='tip_cash',
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='tip_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billlunchmodel',
            name='tip_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
