# Generated by Django 3.2 on 2023-07-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0010_auto_20230725_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdinnermodel',
            name='real_bill_home_oa_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='real_bill_home_oa_count',
            field=models.IntegerField(default=0),
        ),
    ]
