# Generated by Django 3.2 on 2023-07-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0011_auto_20230725_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdinnermodel',
            name='home_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
