# Generated by Django 3.2 on 2023-07-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0013_auto_20230725_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billdinnermodel',
            old_name='derivery_name',
            new_name='delivery_name',
        ),
    ]
