# Generated by Django 3.2 on 2023-07-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0016_auto_20230725_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydetailmodel',
            old_name='wageperhr',
            new_name='wage_per_hour',
        ),
    ]
