# Generated by Django 3.2 on 2023-07-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0018_remove_deliverydetailmodel_home_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydetailmodel',
            old_name='wage_per_hour',
            new_name='wage_per_home',
        ),
    ]
