# Generated by Django 3.2 on 2023-07-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0023_rename_disburselmodel_disbursemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdinnermodel',
            name='delivery_card_amount_in_online_system',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='delivery_card_count_in_online_system',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='delivery_cash_amount_in_online_system',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billdinnermodel',
            name='delivery_cash_count_in_online_system',
            field=models.IntegerField(default=0),
        ),
    ]
