# Generated by Django 3.2 on 2023-07-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0026_billdinnermodel_exceed_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetailmodel',
            name='edc_home_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
