# Generated by Django 3.2 on 2023-07-31 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0027_deliverydetailmodel_edc_home_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdinnermodel',
            name='exceed_credit',
        ),
    ]
