# Generated by Django 3.2 on 2023-07-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordapp', '0028_remove_billdinnermodel_exceed_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdinnermodel',
            name='edc_in_moto_credit',
        ),
        migrations.AddField(
            model_name='deliverydetailmodel',
            name='moto_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
